"""empty message

Revision ID: 180381c40484
Revises: cb3feec1d599
Create Date: 2020-11-10 17:24:37.483376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180381c40484'
down_revision = 'cb3feec1d599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
